-- MySQL Script generated by MySQL Workbench
-- Tue Feb 10 19:31:32 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pmgmt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pmgmt` ;

-- -----------------------------------------------------
-- Schema pmgmt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pmgmt` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pmgmt` ;

-- -----------------------------------------------------
-- Table `pmgmt`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmgmt`.`users` ;

CREATE TABLE IF NOT EXISTS `pmgmt`.`users` (
  `id` INT NOT NULL auto_increment,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `user_name`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmgmt`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmgmt`.`address` ;

CREATE TABLE IF NOT EXISTS `pmgmt`.`address` (
  `id` INT NOT NULL auto_increment,
  `user_id` INT NOT NULL,
  `address_line_1` VARCHAR(255) NOT NULL,
  `address_line_2` VARCHAR(255) NULL,
  `address_line_3` VARCHAR(255) NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `postal_code` VARCHAR(255) NULL,
  `country` VARCHAR(255) NOT NULL,
  `billing_address` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`user_id` ASC),
  CONSTRAINT `userId`
  FOREIGN KEY (`user_id`)
  REFERENCES `pmgmt`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmgmt`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pmgmt`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `pmgmt`.`user_roles` (
  `id` INT NOT NULL auto_increment,
  `role` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
  FOREIGN KEY (`user_id`)
  REFERENCES `pmgmt`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
